name: Check

on:
  pull_request:
  push:

jobs:
  publish:
    name: Publish on PyPI
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: pip install build
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build project
        run: python -m build --sdist --wheel --outdir dist/ .
      - name: Publish on PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}